### ISSUE TITLE
Images not being accessible in Frontend for catalog.

### ISSUE THREAD

**Issue by Aayush3231** [younginnovations/internship-challenges#13]
The images in the news array keeps saying access is denied while fetching the api.
![image](https://github.com/younginnovations/internship-challenges/assets/107331332/c5414fd3-bccf-4bb8-9581-c5665571f0fe)

**Comment by anjhero** [comment]
Thank you for pointing this out. The issue has been fixed. You should be able to access now. Do let us know if you come across any new issues. Best wishes!
